# Packer Status Check Workflow
# 在 Pull Request 時檢查 Packer template 的格式和語法
name: Packer Status Check

# 觸發條件：當有 PR 針對 main branch 時
on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    name: Check Packer Template
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout 程式碼
      - name: Checkout code
        uses: actions/checkout@v3
      
      # 2. 安裝 Packer
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      # 3. 初始化 Packer
      - name: Initialize Packer
        run: |
          cd packer
          packer init .
      
      # 4. 檢查格式（-check 表示只檢查不修改）
      - name: Format check
        run: |
          cd packer
          packer fmt -check -recursive .
      
      # 5. 驗證語法
      - name: Validate template
        run: |
          cd packer
          packer validate -syntax-only .